---
title: "01_load"
author: "Group 29: Helena Møller, Emma Christensen, Frederik Holmstrup, Casper Harreby & Laura Christiansen"
format: html
---

## Loading relevant libraries

```{r}
#| echo: true 
#| eval: true
#| message: false

library("tidyverse")
library("here")
```

## Loading relevant data

The data webpage link are used for a direct load of the data to ensure reproducability

```{r}
#| echo: true 
#| eval: true
#| message: false

#The data is loaded directly from the webpage
raw_data <- read_csv(file = "https://datashare.ed.ac.uk/bitstream/handle/10283/124/IST_corrected.csv?sequence=5&isAllowed=y")
```

## Saving data in a tsv format

The data is saved in a data/\_raw folder on your local directory. The .gitignore is modified to include the entire data folder.

```{r}
#| echo: true 
#| eval: true
#| message: false

# Define the file path using the here terminology
file_path <- here("data/_raw/")

#Checking if the folder path already exists in your local directory
if (!file.exists(file_path)){dir.create(file_path, recursive = TRUE)}

#Write the data to a TSV file
write_tsv(x = raw_data, 
          file = str_c(file_path, "01_dat_load.tsv"))
```
