---
title: "02_clean"
format: html
editor: visual
---

# Data Cleaning

## Loading libraries

```{r}
#| eval: true
library("tidyverse")
```

## Loading data

```{r}
#| eval: true
data <- read_tsv("../data/_raw/01_dat_load.tsv")
```

```{r}
data |> ggplot(mapping = aes(x = HOURLOCAL))+
  geom_histogram()

data |> ggplot(mapping = aes(x = MINLOCAL))+
  geom_histogram()


data |> ggplot(mapping = aes(x = DAYLOCAL))+
  geom_histogram()
```

```{r}

#Replacing all C with NA to indicate missing value
data_clean_noC <- data |> 
  mutate(across(where(is.character), ~ na_if(.,"C")))
```

```{r}

#Replacing all H for M for indicating medium dose (Heparin)
data_clean_noH <- data_clean_noC |> 
  mutate(RXHEP = if_else(RXHEP == "H","M",RXHEP))
```

```{r}

#Replacing all values above 59 in minute and hour with NA
data_clean_truetime <- data_clean_noH |> 
  mutate(MINLOCAL = if_else(MINLOCAL > 59, NA, MINLOCAL),
         HOURLOCAL = if_else(HOURLOCAL > 23, NA, HOURLOCAL))
```

```{r}

#Merging the Hep high and hep medium column, changing unknown to NA
data_clean_correctHepDose <- data_clean_truetime |> 
  mutate(across(c(DMH14,DHH14), ~replace_na(.,""))) |> 
  unite(DMH14, c(DMH14,DHH14), sep = "") |> 
  mutate(DMH14 = na_if(DMH14,"")) |> 
  mutate(across(c(DMH14,DLH14), ~na_if(., "U")))
```

```{r}

#Removing comment columns
data_clean_smaller <- data_clean_correctHepDose |> 
  select(-c(DMAJNCHX,DNOSTRKX,DSIDEX,DDEADX,FDEADX))
```

```{r}
data_clean_properOCcode <- data_clean_smaller |> 
  mutate(OCCODE = case_when(
    OCCODE == 0 ~ NA,
    OCCODE == 1 ~ "dead",
    OCCODE == 2 ~ "dependent",
    OCCODE == 3 ~ "not recovered",
    OCCODE == 4 ~ "recovered",
    OCCODE == 8 ~ NA,
    OCCODE == 9 ~ NA))
```

```{r}
data_clean_properOCcode <- data_clean_properOCcode |> 
  mutate(DEAD = case_when(
    OCCODE == 0 ~ NA,
    OCCODE == 1 ~ "dead",
    OCCODE == 2 ~ "dependent",
    OCCODE == 3 ~ "not recovered",
    OCCODE == 4 ~ "recovered",
    OCCODE == 8 ~ NA,
    OCCODE == 9 ~ NA))
```

```{r}

#Removing ambigious columns
data_clean_properOCcode <-  data_clean_properOCcode |> 
  rename("DEADD" = DDEADD) |> 
  select(-FDEADD)
```

```{r}

data_clean_properDEADcode <- data_clean_properOCcode |> 
  mutate(DEAD1 = if_else(DEAD1 == 1, "1", ""),
         DEAD2 = if_else(DEAD2 == 1, "2", ""),
         DEAD3 = if_else(DEAD3 == 1, "3", ""),
         DEAD4 = if_else(DEAD4 == 1, "4", ""),
         DEAD5 = if_else(DEAD5 == 1, "5", ""),
         DEAD6 = if_else(DEAD6 == 1, "6", ""),
         DEAD7 = if_else(DEAD7 == 1, "7", ""),
         DEAD8 = if_else(DEAD8 == 1, "8", "")) |>
  unite(DEADC, c(DEAD1,DEAD2,DEAD3,DEAD4,DEAD5,DEAD6,DEAD7,DEAD8), sep = "") |> 
  mutate(DEADC = na_if(DEADC,""))
```
