---
title: "06_analysis_2"
format: html
editor: visual
execute: 
  message: FALSE
  warning: FALSE
---

## Libraries

```{r}
#| echo: TRUE
#| eval: TRUE

library("tidyverse")
library("broom")
library("ggrepel")
library("here")
```

## Load Data

```{r}
data <- read_tsv(here("data/03_dat_aug.tsv"))
```

## Analysis

Making a simple linear model for prediction of

-   `EXPDD` (Predicted probability of death/dependence at 6 month)

-   `EXPD6` (Predicted probability of death at 6 month)

-   `EXPD14` (Predicted probability of death at 14 days)

### Model 1

Using `AGE` to see if can be used predict `EXPDD`.

(NOTE: It is not known from the data how

```{r}
model_1 <- data |> 
  filter(STYPE == "LACS") |> 
  lm(data = _,
     EXPDD ~ AGE)
  
```

```{r}
model_1 |> 
  summary()
```

```{r}

p1 <- data |> 
        filter(STYPE == "LACS") |> 
        ggplot(aes(x = AGE, y = log10(EXPDD))) +
        geom_point(color = "PURPLE")

p1
```

### Model 2

```{r}

model_2 <- data |> 
  filter(STYPE == "LACS") |> 
  lm(data = _,
     log2(EXPD6) ~ AGE)
```

```{r}
model_2 |> 
  summary()
```

```{r}
p2 <- data |> 
        filter(STYPE == "LACS") |> 
        ggplot(aes(x = AGE, y = log2(EXPD6))) +
        geom_point(color = "BLUE")

p2
```

### Model 3

```{r}
model_3 <- data |> 
  filter(STYPE == "LACS") |> 
  lm(data = _, log2(EXPD14) ~ AGE)
```

```{r}
model_3 |> 
  summary()
```

```{r}
p3 <- data |> 
        filter(STYPE == "LACS") |> 
        ggplot(aes(x = AGE, y = log2(EXPD14))) +
        geom_point(color = "RED")

p3
```

```{r}
data |> 
  select(data_group) |> 
  group_by(data_group) |> 
  count()
```

## Saving Plots

```{r}
ggsave(filename = here("results/14_keyplot_a.png"), plot = p1)  
ggsave(filename = here("results/14_keyplot_b.png"), plot = p2)
ggsave(filename = here("results/14_keyplot_c.png"), plot = p3)
```
